// examples/react-hooks-example/UserManagement.tsx
/**
 * Příklad použití firestore-helper v React aplikaci s využitím hooks a Context API
 * 
 * React verze: 18.x
 * Přístup: Funkcionální komponenty s hooks a Context API pro sdílení stavu
 */
import React, { createContext, useContext, useEffect, useState, useCallback, ReactNode } from 'react';

// Import z firestore-helper knihovny
import {
    initialize,
    get,
    create,
    update,
    removeDoc,
    Result
} from 'firestore-helper-ts';

// Definice typů pro data
interface User {
    id?: string;
    name: string;
    email: string;
    isActive: boolean;
    lastLogin?: any; // Firestore timestamp
}

// Typy pro kontext
interface UserContextState {
    users: User[];
    loading: boolean;
    error: string | null;
    fetchUsers: () => Promise<void>;
    addUser: (user: Omit<User, 'id'>) => Promise<Result<User>>;
    updateUser: (id: string, data: Partial<User>) => Promise<Result<User>>;
    deleteUser: (id: string) => Promise<Result<unknown>>;
}

// Vytvoření kontextu
const UserContext = createContext<UserContextState | undefined>(undefined);

// Provider komponent pro Firebase a Firestore
interface FirebaseProviderProps {
    children: ReactNode;
    firebaseConfig: {
        apiKey: string;
        authDomain: string;
        projectId: string;
        storageBucket: string;
        messagingSenderId: string;
        appId: string;
    };
}

export const FirebaseProvider: React.FC<FirebaseProviderProps> = ({ children, firebaseConfig }) => {
    // Stav
    const [users, setUsers] = useState<User[]>([]);
    const [loading, setLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [initialized, setInitialized] = useState<boolean>(false);

    // Inicializace Firebase při prvním renderu
    useEffect(() => {
        try {
            if (!initialized) {
                initialize(firebaseConfig);
                setInitialized(true);
                fetchUsers();
            }
        } catch (err) {
            setError('Chyba při inicializaci Firebase');
            console.error(err);
        }
    }, [firebaseConfig, initialized]);

    // Načtení uživatelů s filtrováním aktivních
    const fetchUsers = useCallback(async (onlyActive: boolean = false) => {
        setLoading(true);
        setError(null);

        try {
            const queryOptions = {
                path: 'users',
                orderBy: [['lastLogin', 'desc']],
            };

            // Přidání where podmínky pro aktivní uživatele
            if (onlyActive) {
                queryOptions['where'] = [['isActive', '==', true]];
            }

            const result = await get<User[]>(queryOptions);

            if (result.error) {
                setError(result.error.message);
            } else {
                setUsers(result.data || []);
            }
        } catch (err) {
            setError('Chyba při načítání uživatelů');
            console.error(err);
        } finally {
            setLoading(false);
        }
    }, []);

    // Přidání uživatele
    const addUser = useCallback(async (userData: Omit<User, 'id'>): Promise<Result<User>> => {
        setLoading(true);
        setError(null);

        try {
            const result = await create<User>({
                path: 'users',
                data: {
                    ...userData,
                    lastLogin: new Date(),
                },
            });

            if (result.error) {
                setError(result.error.message);
            } else {
                fetchUsers();
            }

            return result;
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : 'Neznámá chyba';
            setError(`Chyba při vytváření uživatele: ${errorMsg}`);
            console.error(err);
            return { error: { message: errorMsg, code: 'unknown' } };
        } finally {
            setLoading(false);
        }
    }, [fetchUsers]);

    // Aktualizace uživatele
    const updateUser = useCallback(async (userId: string, userData: Partial<User>): Promise<Result<User>> => {
        setLoading(true);
        setError(null);

        try {
            const result = await update<User>({
                path: 'users',
                docId: userId,
                data: userData,
                refetch: true,
            });

            if (result.error) {
                setError(result.error.message);
            } else {
                fetchUsers();
            }

            return result;
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : 'Neznámá chyba';
            setError(`Chyba při aktualizaci uživatele: ${errorMsg}`);
            console.error(err);
            return { error: { message: errorMsg, code: 'unknown' } };
        } finally {
            setLoading(false);
        }
    }, [fetchUsers]);

    // Smazání uživatele
    const deleteUser = useCallback(async (userId: string): Promise<Result<unknown>> => {
        setLoading(true);
        setError(null);

        try {
            const result = await removeDoc({
                path: 'users',
                docId: userId,
            });

            if (result.error) {
                setError(result.error.message);
            } else {
                fetchUsers();
            }

            return result;
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : 'Neznámá chyba';
            setError(`Chyba při mazání uživatele: ${errorMsg}`);
            console.error(err);
            return { error: { message: errorMsg, code: 'unknown' } };
        } finally {
            setLoading(false);
        }
    }, [fetchUsers]);

    // Připravíme hodnotu kontextu
    const contextValue: UserContextState = {
        users,
        loading,
        error,
        fetchUsers,
        addUser,
        updateUser,
        deleteUser,
    };

    return (
        <UserContext.Provider value={contextValue}>
            {children}
        </UserContext.Provider>
    );
};

// Custom hook pro použití UserContext
export const useUsers = () => {
    const context = useContext(UserContext);

    if (context === undefined) {
        throw new Error('useUsers musí být použit uvnitř FirebaseProvider');
    }

    return context;
};

/**
 * Příklad komponenty, která používá náš custom hook
 */
export const UserList: React.FC = () => {
    const { users, loading, error, deleteUser } = useUsers();

    if (loading) return <div>Načítání uživatelů...</div>;
    if (error) return <div>Chyba: {error}</div>;

    return (
        <div>
            <h2>Seznam uživatelů</h2>
            {users.length === 0 ? (
                <p>Žádní uživatelé nebyli nalezeni.</p>
            ) : (
                <ul>
                    {users.map(user => (
                        <li key={user.id} style={{ marginBottom: '12px' }}>
                            <div>
                                <strong>{user.name}</strong> ({user.email})
                                <span style={{ marginLeft: '8px', color: user.isActive ? 'green' : 'red' }}>
                                    {user.isActive ? 'Aktivní' : 'Neaktivní'}
                                </span>
                            </div>
                            <div>
                                <button
                                    onClick={() => deleteUser(user.id!)}
                                    style={{
                                        background: '#f44336',
                                        color: 'white',
                                        border: 'none',
                                        padding: '4px 8px',
                                        borderRadius: '4px',
                                        marginRight: '8px',
                                        cursor: 'pointer'
                                    }}
                                >
                                    Smazat
                                </button>
                                <button
                                    onClick={() => {
                                        // Příklad aktualizace stavu uživatele
                                        const { updateUser } = useUsers();
                                        updateUser(user.id!, { isActive: !user.isActive });
                                    }}
                                    style={{
                                        background: '#4CAF50',
                                        color: 'white',
                                        border: 'none',
                                        padding: '4px 8px',
                                        borderRadius: '4px',
                                        cursor: 'pointer'
                                    }}
                                >
                                    {user.isActive ? 'Deaktivovat' : 'Aktivovat'}
                                </button>
                            </div>
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
};

/**
 * Formulář pro přidání uživatele
 */
export const UserForm: React.FC = () => {
    const { addUser, loading } = useUsers();
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [formError, setFormError] = useState<string | null>(null);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!name || !email) {
            setFormError('Jméno a email jsou povinné');
            return;
        }

        const result = await addUser({
            name,
            email,
            isActive: true,
        });

        if (!result.error) {
            // Reset formuláře
            setName('');
            setEmail('');
            setFormError(null);
        } else {
            setFormError(result.error.message);
        }
    };

    return (
        <div style={{ marginBottom: '24px' }}>
            <h2>Přidat nového uživatele</h2>

            {formError && (
                <div style={{ color: 'red', marginBottom: '12px' }}>
                    {formError}
                </div>
            )}

            <form onSubmit={handleSubmit}>
                <div style={{ marginBottom: '12px' }}>
                    <label style={{ display: 'block', marginBottom: '4px' }}>
                        Jméno:
                    </label>
                    <input
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        disabled={loading}
                        style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid #ccc' }}
                    />
                </div>

                <div style={{ marginBottom: '12px' }}>
                    <label style={{ display: 'block', marginBottom: '4px' }}>
                        Email:
                    </label>
                    <input
                        type="email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        disabled={loading}
                        style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid #ccc' }}
                    />
                </div>

                <button
                    type="submit"
                    disabled={loading}
                    style={{
                        background: '#2196F3',
                        color: 'white',
                        border: 'none',
                        padding: '8px 16px',
                        borderRadius: '4px',
                        cursor: loading ? 'not-allowed' : 'pointer',
                        opacity: loading ? 0.7 : 1
                    }}
                >
                    {loading ? 'Přidávám...' : 'Přidat uživatele'}
                </button>
            </form>
        </div>
    );
};

/**
 * Příklad použití celé aplikace
 */
export const UserManagementApp: React.FC = () => {
    // Konfigurace Firebase
    const firebaseConfig = {
        apiKey: "YOUR_API_KEY",
        authDomain: "your-app.firebaseapp.com",
        projectId: "your-app",
        storageBucket: "your-app.appspot.com",
        messagingSenderId: "YOUR_MESSAGING_ID",
        appId: "YOUR_APP_ID"
    };

    return (
        <FirebaseProvider firebaseConfig={firebaseConfig}>
            <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
                <h1>Správa uživatelů s Firestore Helper</h1>
                <UserForm />
                <UserList />
            </div>
        </FirebaseProvider>
    );
};

// examples/vue-example/UserManagement.vue
<!--
  Příklad použití firestore-helper v Vue.js aplikaci
  
  Vue verze: 3.x
  Přístup: Composition API
-->
<template>
  <div class="user-management">
    <h1>Správa uživatelů s Firestore Helper</h1>

    <!-- Chybová zpráva -->
    <div v-if="error" class="error-message">
      {{ error }}
    </div>

    <!-- Formulář pro přidání uživatele -->
    <div class="user-form">
      <h2>Přidat nového uživatele</h2>
      <form @submit.prevent="createUser">
        <div class="form-group">
          <label for="name">Jméno:</label>
          <input
            type="text"
            id="name"
            v-model="newUser.name"
            required
            :disabled="loading"
          />
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input
            type="email"
            id="email"
            v-model="newUser.email"
            required
            :disabled="loading"
          />
        </div>
        <div class="form-group">
          <label for="department">Oddělení:</label>
          <select
            id="department"
            v-model="newUser.department"
            :disabled="loading"
          >
            <option value="Marketing">Marketing</option>
            <option value="Development">Vývoj</option>
            <option value="Support">Podpora</option>
            <option value="Sales">Obchod</option>
          </select>
        </div>
        <button type="submit" :disabled="loading" class="btn-primary">
          {{ loading ? "Ukládám..." : "Přidat uživatele" }}
        </button>
      </form>
    </div>

    <!-- Seznam uživatelů -->
    <div class="user-list">
      <h2>Seznam uživatelů</h2>

      <div v-if="loading && !users.length" class="loading">
        Načítání uživatelů...
      </div>

      <p v-else-if="!users.length">Žádní uživatelé nebyli nalezeni.</p>

      <table v-else class="user-table">
        <thead>
          <tr>
            <th>Jméno</th>
            <th>Email</th>
            <th>Oddělení</th>
            <th>Stav</th>
            <th>Akce</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in users" :key="user.id">
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.department }}</td>
            <td>
              <span
                class="status-badge"
                :class="{
                  'status-active': user.isActive,
                  'status-inactive': !user.isActive,
                }"
              >
                {{ user.isActive ? "Aktivní" : "Neaktivní" }}
              </span>
            </td>
            <td class="actions">
              <button
                class="btn-action btn-toggle"
                @click="toggleUserStatus(user)"
                :disabled="loading"
              >
                {{ user.isActive ? "Deaktivovat" : "Aktivovat" }}
              </button>
              <button
                class="btn-action btn-delete"
                @click="deleteUser(user.id)"
                :disabled="loading"
              >
                Smazat
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, reactive, onMounted } from "vue";
import {
  initialize,
  get,
  create,
  update,
  removeDoc,
} from "firestore-helper-ts";

// Definice typů pro TypeScript
interface User {
  id?: string;
  name: string;
  email: string;
  department: string;
  isActive: boolean;
  createdAt?: any; // Firestore timestamp
}

export default defineComponent({
  name: "UserManagement",

  setup() {
    // Stav
    const users = ref<User[]>([]);
    const loading = ref(false);
    const error = ref<string | null>(null);

    // Nový uživatel - formulářová data
    const newUser = reactive<Omit<User, "id" | "isActive" | "createdAt">>({
      name: "",
      email: "",
      department: "Development",
    });

    // Inicializace Firebase
    const initializeFirebase = () => {
      try {
        initialize({
          apiKey: import.meta.env.VITE_FIREBASE_API_KEY || "YOUR_API_KEY",
          authDomain:
            import.meta.env.VITE_FIREBASE_AUTH_DOMAIN ||
            "your-app.firebaseapp.com",
          projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || "your-app",
          storageBucket:
            import.meta.env.VITE_FIREBASE_STORAGE_BUCKET ||
            "your-app.appspot.com",
          messagingSenderId:
            import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID ||
            "YOUR_MESSAGING_ID",
          appId: import.meta.env.VITE_FIREBASE_APP_ID || "YOUR_APP_ID",
        });
      } catch (err) {
        error.value = "Chyba při inicializaci Firebase";
        console.error(err);
      }
    };

    // Načtení uživatelů
    const fetchUsers = async () => {
      loading.value = true;
      error.value = null;

      try {
        const result = await get<User[]>({
          path: "users",
          orderBy: [["createdAt", "desc"]],
          limit: 20,
        });

        if (result.error) {
          error.value = result.error.message;
        } else {
          users.value = result.data || [];
        }
      } catch (err) {
        error.value = "Chyba při načítání uživatelů";
        console.error(err);
      } finally {
        loading.value = false;
      }
    };

    // Vytvoření uživatele
    const createUser = async () => {
      loading.value = true;
      error.value = null;

      try {
        const result = await create<User>({
          path: "users",
          data: {
            ...newUser,
            isActive: true,
            createdAt: new Date(),
          },
        });

        if (result.error) {
          error.value = result.error.message;
        } else {
          // Reset formuláře
          newUser.name = "";
          newUser.email = "";
          newUser.department = "Development";

          // Načtení aktualizovaných dat
          fetchUsers();
        }
      } catch (err) {
        error.value = "Chyba při vytváření uživatele";
        console.error(err);
      } finally {
        loading.value = false;
      }
    };

    // Přepnutí stavu uživatele (aktivní/neaktivní)
    const toggleUserStatus = async (user: User) => {
      if (!user.id) return;

      loading.value = true;
      error.value = null;

      try {
        const result = await update<User>({
          path: "users",
          docId: user.id,
          data: {
            isActive: !user.isActive,
          },
        });

        if (result.error) {
          error.value = result.error.message;
        } else {
          fetchUsers();
        }
      } catch (err) {
        error.value = "Chyba při aktualizaci uživatele";
        console.error(err);
      } finally {
        loading.value = false;
      }
    };

    // Smazání uživatele
    const deleteUser = async (userId: string) => {
      if (!confirm("Opravdu chcete smazat tohoto uživatele?")) {
        return;
      }

      loading.value = true;
      error.value = null;

      try {
        const result = await removeDoc({
          path: "users",
          docId: userId,
        });

        if (result.error) {
          error.value = result.error.message;
        } else {
          fetchUsers();
        }
      } catch (err) {
        error.value = "Chyba při mazání uživatele";
        console.error(err);
      } finally {
        loading.value = false;
      }
    };

    // Inicializace při načtení komponenty
    onMounted(() => {
      initializeFirebase();
      fetchUsers();
    });

    return {
      users,
      loading,
      error,
      newUser,
      createUser,
      toggleUserStatus,
      deleteUser,
    };
  },
});
</script>

<style scoped>
.user-management {
  font-family: Arial, sans-serif;
  max-width: 1000px;
  margin: 0 auto;
  padding: 20px;
}

h1 {
  color: #333;
  margin-bottom: 20px;
}

h2 {
  margin-top: 30px;
  margin-bottom: 15px;
  color: #444;
}

.error-message {
  background-color: #ffebee;
  color: #c62828;
  padding: 10px;
  border-radius: 4px;
  margin-bottom: 20px;
}

.user-form {
  background-color: #f5f5f5;
  padding: 20px;
  border-radius: 4px;
  margin-bottom: 30px;
}

.form-group {
  margin-bottom: 15px;
}

label {
  display: block;
  margin-bottom: 5px;
  font-weight: 600;
}

input,
select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

.user-table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
}

.user-table th,
.user-table td {
  border: 1px solid #ddd;
  padding: 12px;
  text-align: left;
}

.user-table th {
  background-color: #f5f5f5;
  font-weight: 600;
}

.actions {
  display: flex;
  gap: 8px;
}

.btn-primary {
  background-color: #1976d2;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}

.btn-primary:hover {
  background-color: #1565c0;
}

.btn-primary:disabled {
  background-color: #bbdefb;
  cursor: not-allowed;
}

.btn-action {
  border: none;
  padding: 5px 10px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-toggle {
  background-color: #26a69a;
  color: white;
}

.btn-toggle:hover {
  background-color: #00897b;
}

.btn-delete {
  background-color: #e53935;
  color: white;
}

.btn-delete:hover {
  background-color: #c62828;
}

.btn-action:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.status-badge {
  padding: 4px 8px;
  border-radius: 10px;
  font-size: 14px;
}

.status-active {
  background-color: #c8e6c9;
  color: #2e7d32;
}

.status-inactive {
  background-color: #ffccbc;
  color: #d84315;
}

.loading {
  font-style: italic;
  color: #757575;
}
</style>
